name: "Feature suggestion"
description: Suggest a new feature to help the project improve.
title: "feat: TITLE"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please provide a detailed description of your feature suggestion
      placeholder: Please provide a detailed description of the feature you would like to suggest...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By creating this issue I made sure that ...
      options:
        - label: There is no issue already suggesting my feature.
          required: true
